# Generated by Django 2.1 on 2018-08-21 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='text_name',
        ),
    ]
