# Generated by Django 2.1 on 2018-08-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_person_text_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
